<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>js Error Handling Using try and catch</title>
</head>
<body>
    try catch block is used for error handling, normally when error occured further execution stops, but when we use try and catch we print in on console so the further 
    execution won't stops
    <script>

    //    try{
    //    savitri

    //    throw new Error("throwing custom error");
       
    //    }
    //    catch(error){
        // console.log("i am an error");    //this will print custom error message
        // console.log(error);              //this one prints the error given by browser
        // console.log(error.name);         //this will print the name of error ex- ReferenceError, ArrayIndexOutOfBoundError ect.
        // console.log(error.message);         //this will print the message given by browser
    //    }
    // throw new Error("i am an error");        // this is used to throw external user defined errors


    // Finally clause

    // try{
    //     let a =0;
    //     console.log(program);
    //     console.log('Program ran successfully');
        
        
    // }
    // catch(error){
    //     console.log("this is an error");
    //     console.log(n);
        
        
    // }
    // finally{                                                       // finally block ensure that your code will run in any situation, even if error occured in try and catch block
    //     console.log('code after running program successfully');
        
    // }
    
    </script>
</body>
</html>